### ISSUE TITLE
Add persistence

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/sleep#1]
Persisting signals and picking them up on a service restart could be a useful addition. This would allow us to safely sleep for long periods of time

**Comment by hansmosh** [comment]
If the sleep interval has passed between the stop and star should the signals be dropped?

Ex. Sleep interval 1 hour. Process a signal and stop the service. Start the service two hours later. Does the signal get notified on start or is it dropped?

**Comment by mattdodge** [comment]
Good question, I think dropped by default, but maybe a configurable option
